# Generated by Django 6.0.5 on 2026-07-01 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('ANNUAL', 'Annual'), ('BI_ANNUAL', 'Bi-Annual'), ('QUARTERLY', 'Quarterly')], default='ANNUAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('scoring_scale', models.PositiveSmallIntegerField(choices=[(5, '1-5 Scale'), (10, '1-10 Scale')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appraisal Cycle',
                'verbose_name_plural': 'Appraisal Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RETURNED_TO_STAFF', 'Returned to Staff'), ('REVIEWED', 'Reviewed'), ('RETURNED_TO_SUPERVISOR', 'Returned to Supervisor'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='NOT_STARTED', max_length=25)),
                ('self_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_supervisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_appraisals', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='appraisals.appraisalcycle')),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight of this category in the overall competency score.', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_categories', to='appraisals.appraisalcycle')),
            ],
            options={
                'verbose_name': 'Competency Category',
                'verbose_name_plural': 'Competency Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appraisals.competencycategory')),
            ],
            options={
                'verbose_name': 'Competency Item',
                'verbose_name_plural': 'Competency Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HODReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('RETURNED', 'Returned')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_review', to='appraisals.appraisal')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HOD Review',
                'verbose_name_plural': 'HOD Reviews',
            },
        ),
        migrations.CreateModel(
            name='KPICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight of this category in the overall KPI score.', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_categories', to='appraisals.appraisalcycle')),
            ],
            options={
                'verbose_name': 'KPI Category',
                'verbose_name_plural': 'KPI Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appraisals.kpicategory')),
            ],
            options={
                'verbose_name': 'KPI Item',
                'verbose_name_plural': 'KPI Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SelfAppraisalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_achievements', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('training_needs', models.TextField(blank=True)),
                ('goals_next_period', models.TextField(blank=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_detail', to='appraisals.appraisal')),
            ],
            options={
                'verbose_name': 'Self-Appraisal Detail',
                'verbose_name_plural': 'Self-Appraisal Details',
            },
        ),
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_review', to='appraisals.appraisal')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Review',
                'verbose_name_plural': 'Supervisor Reviews',
            },
        ),
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('supervisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('staff_comment', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='appraisals.appraisal')),
                ('competency_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.competencyitem')),
            ],
            options={
                'verbose_name': 'Competency Score',
                'verbose_name_plural': 'Competency Scores',
                'unique_together': {('appraisal', 'competency_item')},
            },
        ),
        migrations.CreateModel(
            name='KPIScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(blank=True, help_text='What was the target for this KPI.')),
                ('achievement', models.TextField(blank=True, help_text='What was achieved against the target.')),
                ('self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('supervisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('staff_comment', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_scores', to='appraisals.appraisal')),
                ('kpi_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.kpiitem')),
            ],
            options={
                'verbose_name': 'KPI Score',
                'verbose_name_plural': 'KPI Scores',
                'unique_together': {('appraisal', 'kpi_item')},
            },
        ),
    ]
