# Generated by Django 6.0.6 on 2026-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='hod_return_notes',
            field=models.TextField(blank=True, help_text='Reason provided by the HOD when returning the appraisal to the supervisor.'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='supervisor_return_notes',
            field=models.TextField(blank=True, help_text='Reason provided by the supervisor when returning the appraisal to the staff.'),
        ),
    ]
