# Generated by Django 6.0.6 on 2026-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_appraisal_hod_return_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyscore',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Optional file attachment to provide evidence for this Competency.', null=True, upload_to='evidence/competencies/'),
        ),
        migrations.AddField(
            model_name='kpiscore',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Optional file attachment to provide evidence for this KPI.', null=True, upload_to='evidence/kpis/'),
        ),
        migrations.AddField(
            model_name='selfappraisaldetail',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Optional general file attachment for the narrative section.', null=True, upload_to='evidence/narratives/'),
        ),
    ]
