# Generated by Django 6.0.5 on 2026-07-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_competencyscore_evidence_file_kpiscore_evidence_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_supervisor_field', models.BooleanField(default=False, help_text='If True, this field is filled by the supervisor instead of the staff member.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_fields', to='appraisals.appraisalcycle')),
            ],
            options={
                'verbose_name': 'Narrative Field',
                'verbose_name_plural': 'Narrative Fields',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NarrativeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/narratives/')),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_responses', to='appraisals.appraisal')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.narrativefield')),
            ],
            options={
                'verbose_name': 'Narrative Response',
                'verbose_name_plural': 'Narrative Responses',
                'unique_together': {('appraisal', 'field')},
            },
        ),
        migrations.DeleteModel(
            name='SelfAppraisalDetail',
        ),
    ]
