# Generated by Django 6.0.5 on 2026-07-03 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_narrativefield_narrativeresponse_and_more'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcycle',
            name='target_departments',
            field=models.ManyToManyField(blank=True, help_text='If set, only staff in these departments will be assigned this cycle.', to='departments.department'),
        ),
        migrations.AddField(
            model_name='appraisalcycle',
            name='target_staff',
            field=models.ManyToManyField(blank=True, help_text='If set, these specific staff will be assigned this cycle.', related_name='targeted_cycles', to=settings.AUTH_USER_MODEL),
        ),
    ]
