# Generated by Django 6.0.5 on 2026-07-03 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0005_appraisalcycle_target_departments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcycle',
            name='excluded_staff',
            field=models.ManyToManyField(blank=True, help_text='Staff in this list will never be assigned this cycle.', related_name='excluded_cycles', to=settings.AUTH_USER_MODEL),
        ),
    ]
