# Generated by Django 6.0.6 on 2026-07-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_appraisalcycle_excluded_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='current_step_number',
            field=models.PositiveIntegerField(default=0, help_text='0 = not yet submitted. 1+ = the step currently awaiting action.'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='staff_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='hod_return_notes',
            field=models.TextField(blank=True, help_text='Reason provided by the HOD when returning the appraisal.'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted — Awaiting Step 1'), ('AWAITING_STEP_REVIEW', 'Awaiting Reviewer Action'), ('RETURNED_TO_STAFF', 'Returned to Staff'), ('RETURNED_TO_REVIEWER', 'Returned to Previous Reviewer'), ('APPROVED', 'Fully Approved'), ('STAFF_ACKNOWLEDGED', 'Staff Acknowledged'), ('ARCHIVED', 'Archived')], default='NOT_STARTED', max_length=25),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='supervisor_return_notes',
            field=models.TextField(blank=True, help_text='Reason provided when returning the appraisal to the staff.'),
        ),
        migrations.AlterField(
            model_name='hodreview',
            name='action',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('RETURNED', 'Returned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='narrativefield',
            name='is_supervisor_field',
            field=models.BooleanField(default=False, help_text='If True, this field is filled by the first-step approver instead of the staff member.'),
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'Standard 4-Step Review' or 'HOD Override Process'.", max_length=200)),
                ('is_general', models.BooleanField(default=False, help_text='If True, this is the default process applied to all staff in this cycle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approval_processes', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_processes', to='appraisals.appraisalcycle')),
            ],
            options={
                'verbose_name': 'Approval Process',
                'verbose_name_plural': 'Approval Processes',
                'ordering': ['-is_general', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appraisal',
            name='override_process',
            field=models.ForeignKey(blank=True, help_text="If set, overrides the cycle's general approval process for this staff member.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_appraisals', to='appraisals.approvalprocess'),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Ordering within the process. Step 1 is actioned first.')),
                ('label', models.CharField(help_text="Display label, e.g. 'Supervisor Review', 'HOD Moderation'.", max_length=200)),
                ('role_required', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department'), ('DIRECTORATE', 'Director/Executive'), ('HR_ADMIN', 'HR Administrator')], help_text='Which role is allowed to action this step.', max_length=20)),
                ('action_label_approve', models.CharField(default='Approve & Forward', help_text='Button label for the approve action.', max_length=100)),
                ('action_label_return', models.CharField(default='Return for Revision', help_text='Button label for the return action.', max_length=100)),
                ('can_score', models.BooleanField(default=True, help_text='If True, the approver at this step can enter/edit scores.')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='appraisals.approvalprocess')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['step_number'],
                'unique_together': {('process', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='AppraisalApprovalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_assignments', to='appraisals.appraisal')),
                ('approver', models.ForeignKey(blank=True, help_text='The specific user assigned to action this step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_assignments', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='appraisals.approvalstep')),
            ],
            options={
                'verbose_name': 'Approval Assignment',
                'verbose_name_plural': 'Approval Assignments',
                'ordering': ['step__step_number'],
                'unique_together': {('appraisal', 'step')},
            },
        ),
    ]
