# Generated by Django 6.0.5 on 2026-07-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_appraisal_current_step_number_and_more'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcycle',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this cycle is scoped to. All targeting is filtered by this branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='branches.branch'),
        ),
    ]
