# Generated by Django 6.0.5 on 2026-07-19 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0008_appraisalcycle_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Section A: KPIs & Core Duties'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional instructions shown above the section.')),
                ('section_weight', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight of this section in the overall score (0-100). Set to 0 for non-scored sections.', max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sections', to='appraisals.appraisalcycle')),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display name, e.g. 'Revenue Target Achieved'", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Help text shown beneath the field.')),
                ('field_type', models.CharField(choices=[('NARRATIVE', 'Narrative (Text)'), ('SCORE', 'Score (Numeric)'), ('SCORE_COMMENT', 'Score + Comment'), ('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multiple Select')], default='NARRATIVE', max_length=20)),
                ('filled_by', models.CharField(choices=[('APPRAISEE', 'Appraisee (Staff)'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department'), ('DIRECTORATE', 'Director/Executive'), ('HR_ADMIN', 'HR Administrator')], default='APPRAISEE', help_text='Which role is responsible for filling this field.', max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, help_text='Maximum achievable score for this field.', max_digits=7)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, help_text='Minimum score for this field (usually 0).', max_digits=7)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of option strings for SINGLE_SELECT or MULTI_SELECT fields.')),
                ('reviewer_can_score', models.BooleanField(default=False, help_text='If True and filled_by=APPRAISEE, the designated reviewer can also give a score on this field.')),
                ('reviewer_score_role', models.CharField(blank=True, choices=[('APPRAISEE', 'Appraisee (Staff)'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department'), ('DIRECTORATE', 'Director/Executive'), ('HR_ADMIN', 'HR Administrator')], help_text='Which reviewer role provides the score (Mode B).', max_length=20)),
                ('reviewer_score_max', models.DecimalField(blank=True, decimal_places=2, default=10, help_text='Maximum score the reviewer can give on this field (Mode B).', max_digits=7)),
                ('reviewer_can_comment', models.BooleanField(default=False, help_text='If True and filled_by=APPRAISEE, the designated reviewer can add a comment on this field.')),
                ('reviewer_comment_role', models.CharField(blank=True, choices=[('APPRAISEE', 'Appraisee (Staff)'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department'), ('DIRECTORATE', 'Director/Executive'), ('HR_ADMIN', 'HR Administrator')], help_text='Which reviewer role provides the comment (Mode B).', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this field must be filled before the form can be submitted.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='appraisals.formsection')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('PRIMARY', 'Primary Response'), ('REVIEWER_SCORE', 'Reviewer Score'), ('REVIEWER_COMMENT', 'Reviewer Comment')], default='PRIMARY', max_length=20)),
                ('text_response', models.TextField(blank=True, help_text='Response for NARRATIVE fields or the comment part of SCORE_COMMENT.')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric score for SCORE, SCORE_COMMENT, or reviewer Mode B score.', max_digits=7, null=True)),
                ('selected_options', models.JSONField(blank=True, default=list, help_text='Selected option(s) for SINGLE_SELECT and MULTI_SELECT fields.')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/form_fields/')),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='appraisals.appraisal')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='appraisals.formfield')),
                ('responded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_field_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Field Response',
                'verbose_name_plural': 'Form Field Responses',
                'ordering': ['field__order'],
                'unique_together': {('appraisal', 'field', 'responded_by', 'response_type')},
            },
        ),
    ]
