# Generated by Django 6.0.5 on 2026-07-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0010_appraisalcycle_archived_at_and_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='The specific user assigned to action this step for all appraisals using this process (overrides dynamic role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_step_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
