# Generated by Django 6.0.5 on 2026-07-21 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0011_approvalstep_approver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_step_number', models.PositiveIntegerField(default=0)),
                ('to_step_number', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_logs', to='appraisals.appraisal')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_log_entries', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_log_entries', to='appraisals.approvalstep')),
            ],
            options={
                'verbose_name': 'Return Log',
                'verbose_name_plural': 'Return Logs',
                'ordering': ['-returned_at'],
            },
        ),
    ]
