# Generated by Django 6.0.5 on 2026-07-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0012_add_return_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='filled_by',
            field=models.CharField(choices=[('APPRAISEE', 'Appraisee (Staff)'), ('SUPERVISOR', 'Supervisor (Role)'), ('HOD', 'Head of Department (Role)'), ('DIRECTORATE', 'Director/Executive (Role)'), ('HR_ADMIN', 'HR Administrator (Role)'), ('STEP_1', 'Step 1 Approver (Process)'), ('STEP_2', 'Step 2 Approver (Process)'), ('STEP_3', 'Step 3 Approver (Process)'), ('STEP_4', 'Step 4 Approver (Process)'), ('STEP_5', 'Step 5 Approver (Process)')], default='APPRAISEE', help_text='Which role is responsible for filling this field.', max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='reviewer_comment_role',
            field=models.CharField(blank=True, choices=[('APPRAISEE', 'Appraisee (Staff)'), ('SUPERVISOR', 'Supervisor (Role)'), ('HOD', 'Head of Department (Role)'), ('DIRECTORATE', 'Director/Executive (Role)'), ('HR_ADMIN', 'HR Administrator (Role)'), ('STEP_1', 'Step 1 Approver (Process)'), ('STEP_2', 'Step 2 Approver (Process)'), ('STEP_3', 'Step 3 Approver (Process)'), ('STEP_4', 'Step 4 Approver (Process)'), ('STEP_5', 'Step 5 Approver (Process)')], help_text='Which reviewer role provides the comment (Mode B).', max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='reviewer_score_role',
            field=models.CharField(blank=True, choices=[('APPRAISEE', 'Appraisee (Staff)'), ('SUPERVISOR', 'Supervisor (Role)'), ('HOD', 'Head of Department (Role)'), ('DIRECTORATE', 'Director/Executive (Role)'), ('HR_ADMIN', 'HR Administrator (Role)'), ('STEP_1', 'Step 1 Approver (Process)'), ('STEP_2', 'Step 2 Approver (Process)'), ('STEP_3', 'Step 3 Approver (Process)'), ('STEP_4', 'Step 4 Approver (Process)'), ('STEP_5', 'Step 5 Approver (Process)')], help_text='Which reviewer role provides the score (Mode B).', max_length=20),
        ),
    ]
