# Generated by Django 6.0.6 on 2026-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, help_text='Optional profile photograph.', null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
    ]
