# Generated by Django 6.0.6 on 2026-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department'), ('DIRECTORATE', 'Director/Executive'), ('HR_ADMIN', 'HR Administrator')], default='STAFF', help_text='Organisational role that determines access permissions.', max_length=20, verbose_name='Role'),
        ),
    ]
