# Generated by Django 6.0.5 on 2026-07-19 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the branch.', max_length=200, unique=True)),
                ('code', models.CharField(help_text="Short unique code for the branch (e.g. 'HQ', 'ZO-IKJ').", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the branch location or purpose.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments that operate within this branch.', related_name='branches', to='departments.department')),
                ('members', models.ManyToManyField(blank=True, help_text='Staff members assigned to this branch.', related_name='branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
    ]
