# Generated by Django 6.0.6 on 2026-07-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='Exam instructions or introductory text shown before the exam starts.')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Time allowed to complete the exam in minutes.')),
                ('pass_mark', models.PositiveSmallIntegerField(default=50, help_text='Minimum percentage score required to pass.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('randomise_questions', models.BooleanField(default=True, help_text='If True, question order will be shuffled for each attempt.')),
                ('allow_multiple_attempts', models.BooleanField(default=False, help_text='If True, staff can retake the exam after completing it.')),
                ('show_answers_after', models.BooleanField(default=True, help_text='If True, staff can see the correct answers after completing the exam.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CBT Exam',
                'verbose_name_plural': 'CBT Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('TIMED_OUT', 'Timed Out')], default='NOT_STARTED', max_length=15)),
                ('question_order', models.TextField(default='[]', help_text='JSON-encoded list of CBTQuestion PKs in presentation order.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.PositiveIntegerField(default=0, help_text='Total marks earned.')),
                ('total_marks', models.PositiveIntegerField(default=0, help_text='Total marks possible.')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cbt.cbtexam')),
            ],
            options={
                'verbose_name': 'CBT Attempt',
                'verbose_name_plural': 'CBT Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to_all', models.BooleanField(default=False, help_text='If True, every active staff member is assigned this exam.')),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional deadline by which the exam must be completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_departments', models.ManyToManyField(blank=True, help_text='Departments whose staff are assigned to this exam.', related_name='cbt_assignments', to='departments.department')),
                ('target_staff', models.ManyToManyField(blank=True, help_text='Specific staff members assigned to this exam.', related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cbt.cbtexam')),
            ],
            options={
                'verbose_name': 'CBT Assignment',
                'verbose_name_plural': 'CBT Assignments',
            },
        ),
        migrations.CreateModel(
            name='CBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text.')),
                ('marks', models.PositiveSmallIntegerField(default=1, help_text='Marks awarded for a correct answer.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.cbtexam')),
            ],
            options={
                'verbose_name': 'CBT Question',
                'verbose_name_plural': 'CBT Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CBTOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cbt.cbtquestion')),
            ],
            options={
                'verbose_name': 'CBT Option',
                'verbose_name_plural': 'CBT Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CBTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cbt.cbtattempt')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbt.cbtoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.cbtquestion')),
            ],
            options={
                'verbose_name': 'CBT Answer',
                'verbose_name_plural': 'CBT Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
