# Generated by Django 6.0.5 on 2026-07-01 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPRAISAL_SUBMITTED', 'Appraisal Submitted'), ('APPRAISAL_REVIEWED', 'Appraisal Reviewed'), ('APPRAISAL_RETURNED', 'Appraisal Returned'), ('APPRAISAL_APPROVED', 'Appraisal Approved'), ('CYCLE_CREATED', 'Cycle Created'), ('CYCLE_ACTIVATED', 'Cycle Activated'), ('CYCLE_CLOSED', 'Cycle Closed'), ('GENERAL', 'General')], default='GENERAL', help_text='The category of this notification.', max_length=50, verbose_name='Notification Type')),
                ('title', models.CharField(help_text='A short summary of the notification.', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='The full notification message body.', verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this notification.', verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('related_appraisal', models.ForeignKey(blank=True, help_text='The appraisal associated with this notification (if any).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appraisals.appraisal', verbose_name='Related Appraisal')),
                ('sender', models.ForeignKey(blank=True, help_text='The user who triggered this notification (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
